'tz|7 rework'
sixtykz/java-kanban pull request #2
Opened 2024-04-21 21:11 UTC by sixtykz

2024-04-22 17:45 UTC, dgumich requested changes

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public void FileBackedTaskManager(File file) {
Зачем этот конструктор, если нигде не используешь?

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public enum TaskType {
Это должно быть в отдельном файле, а не внутри FileBackedTasksManager

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public class ManagerSaveException extends RuntimeException {
Это так же должно быть в отдельном файле, а не внутри FileBackedTasksManager

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +            fileBackedTasksManager = (FileBackedTasksManager) ois.readObject();
Что это такое? Тут должна быть логика загрузки из файла. То есть мы читаем строки, парсим их в задачи, кладем в нужные мапы и тд.

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +            e.printStackTrace();
Здесь так же надо бросать свое исключение ManagerSaveException

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    private final HashMap<Integer, Task> tasks = new HashMap<>();
FileBackedTasksManager не должно быть своих мап, мы работаем только с мапами из InMemoryTaskManager.

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public int generateId() {
Этой логики не должно быть в этой классе. С айди работаем только в InMemoryTaskManager

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +            for (Task task : tasks.values()) {
Почему сохраняем только задачи? А как же подзадачи/эпики?

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public void completeTask(int taskId) {
Это что за метод? Откуда его взял? Зачем он?

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public void updateTask(int taskId, String name, Status status, String description) {
Это что за метод? Откуда ты его взял? У нас уже есть метод public void updateTask(Task task)

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public void assignTaskToEpic(int taskId, int epicId) {
Это что за метод? Откуда ты его взял?

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public void deleteTaskById(int taskId) {
Не правильная реализация метода. В FileBackedTasksManager мы только вызываем метод у родителя и добавляем логику сохранения (как сделал в методе public void addTask(Task task))

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public void deleteEpicById(int epicId) {
Не правильная реализация метода. В FileBackedTasksManager мы только вызываем метод у родителя и добавляем логику сохранения (как сделал в методе public void addTask(Task task))

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public void deleteSubTaskById(int subTaskId) {
Не правильная реализация метода. В FileBackedTasksManager мы только вызываем метод у родителя и добавляем логику сохранения (как сделал в методе public void addTask(Task task))

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public void deleteAllTasks() {
Не правильная реализация метода. В FileBackedTasksManager мы только вызываем метод у родителя и добавляем логику сохранения (как сделал в методе public void addTask(Task task))

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public void deleteAllEpics() {
Не правильная реализация метода. В FileBackedTasksManager мы только вызываем метод у родителя и добавляем логику сохранения (как сделал в методе public void addTask(Task task))

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public void deleteAllSubTask() {
Не правильная реализация метода. В FileBackedTasksManager мы только вызываем метод у родителя и добавляем логику сохранения (как сделал в методе public void addTask(Task task))

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public Task getTaskById(int taskId) {
Не правильная реализация метода. В FileBackedTasksManager мы только вызываем метод у родителя и добавляем логику сохранения (как сделал в методе public void addTask(Task task))

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public Epic getEpicById(int epicId) {
Не правильная реализация метода. В FileBackedTasksManager мы только вызываем метод у родителя и добавляем логику сохранения (как сделал в методе public void addTask(Task task))

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public Subtask getSubTaskById(int subTaskId) {
Не правильная реализация метода. В FileBackedTasksManager мы только вызываем метод у родителя и добавляем логику сохранения (как сделал в методе public void addTask(Task task))

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public List<Task> getAllTask() {
Не правильная реализация метода: при получении всех задач у нас ничего не поменяется (задачи/подзадачи/эпики в мапах останутся такими же). Соответственно сохранять не надо. Поэтому этот метод даже не надо переопределять.

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public List<Epic> getAllEpic() {
Не правильная реализация метода: при получении всех задач у нас ничего не поменяется (задачи/подзадачи/эпики в мапах останутся такими же). Соответственно сохранять не надо. Поэтому этот метод даже не надо переопределять.

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public List<Subtask> getAllSubTask() {
Не правильная реализация метода: при получении всех задач у нас ничего не поменяется (задачи/подзадачи/эпики в мапах останутся такими же). Соответственно сохранять не надо. Поэтому этот метод даже не надо переопределять.

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public List<Subtask> getAllSubTaskByEpicId(int epicId) {
Не правильная реализация метода: при получении всех задач у нас ничего не поменяется (задачи/подзадачи/эпики в мапах останутся такими же). Соответственно сохранять не надо. Поэтому этот метод даже не надо переопределять.

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public void updateTask(Task task) {
Не правильная реализация метода. В FileBackedTasksManager мы только вызываем метод у родителя и добавляем логику сохранения (как сделал в методе public void addTask(Task task))

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public void updateEpic(Epic epic) {
Не правильная реализация метода. В FileBackedTasksManager мы только вызываем метод у родителя и добавляем логику сохранения (как сделал в методе public void addTask(Task task))

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    private void updateStatusEpic(Epic epic) {
Тут нет необходимости в данной логике. Она должна быть только в родительском классе.

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public void updateSubtask(Subtask subTask) {
Не правильная реализация метода. В FileBackedTasksManager мы только вызываем метод у родителя и добавляем логику сохранения (как сделал в методе public void addTask(Task task))

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public List<Task> getHistory() {
Зачем переопределять данные метод, если логика никак не поменялась?

2024-04-22 17:45 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    private final HistoryManager historyManager = Managers.getDefaultHistory();
А это поле зачем нам? У нас уже есть historyManager в InMemoryTaskManager, должны использовать его.

2024-04-25 19:53 UTC, dgumich requested changes

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    private static File path;
Зачем нужно это поле, если оно не используется?

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public static File getFile() {
Зачем нужен геттер, если он не используется?

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +//убрал отсюда мапы, historyManager и айди
Комментарии по поводу того, что сделал лучше оставляй в пул реквесте. Просто отвечай на мой комментарий. 
В коде не должно быть комментариев.

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +
Код стайл, столько пустых строк. Надо убрать

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +// перенес TaskType в отдельный файл
Тут наоборот нет пустой строки между методами.

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +        try (PrintWriter writer = new PrintWriter(file)) {
Зачем для каждого типа делаешь отдельный блок try? Всё можно сделать в одном, просто сначала будет цикл записи задач, потом эпиков, потом подзадач.

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +                writer.println(task.toCSV());
Метод task.toCSV() возвращает boolean, а не строковую не конвертирует задачу в строку. Аналогично для эпика/подзадачи. Надо исправить.

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public static Task fromString(String value) {
Метод нигде не вызывается.

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +    public String toString(Task task) {
Метод нигде не вызывается

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +            while ((line = br.readLine()) != null) {
line считываешь, но нигде не используешь.

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +                    Task task = null;
Логика чтения из файла реализована не правильно:
1) Надо считать строку (считал, но ничего с ней не делаешь)
2) Распарсить эту строку в задачу/подзадачу/эпик. Для этого написать метод, который будет это сделать. Этой логики нет.
3) Сложить в нужную мапу (в зависимости от типа) - эта логика есть, но реализована не правильно.
Надо складывать на прямую в нужную мапу, а не через методы addTask/addEpic/addSubTask.
Почему? Тут два момента:
- Эти методы вызывают метод save. Получается, что мы считали из файла и тут же его будем перезаписывать. Если произойдет ошибка, то мы можем потерять оригинальное состояние файла. 
-  Эти методы сетапят айдишник. Что плохо, так как мы записали задачи в файл с своими айди и под ними ожидаем их найти. 
4) При чтении из файла, надо найти наибольший айди у задач, и присвоить его значение +1 полю protected int  id в InMemoryTaskManager

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +                    fileBackedTasksManager.getTaskById(task.getId());
Зачем тут вызова .getTaskById(task.getId())?

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/InMemoryTaskManager.java
> +    public void assignTaskToEpic(int taskId, int epicId) {
Нам не нужен данный метод, надо удалить

2024-04-25 19:53 UTC, dgumich commented on src/main/java/service/InMemoryTaskManager.java
> +    protected void updateTask(int taskId, String name, Status status, String description) {
Надо удалить данные методы, так как они не используются и не нужны:
updateTask(int taskId, String name, Status status, String description)
completeTask(int taskId)
addTask(Task task)
addSubTask(Subtask subTask)

2024-04-25 19:53 UTC, dgumich commented on src/main/java/tasks/Task.java
> +import main.java.service.FileBackedTasksManager;
Не используемый импорт

2024-04-25 19:53 UTC, dgumich commented on src/main/java/tasks/Task.java
> +    public Task(TaskType type, String description) {
Зачем эти конструкторы, если они пустые?

2024-04-25 19:53 UTC, dgumich commented on src/main/java/tasks/Task.java
> +        return true;
Логика метода не верная

2024-04-25 19:53 UTC, dgumich commented on src/main/java/tasks/TaskType.java
> +    TASK,
Энам сделал, а в самих задачах/подзадачах/эпиках не используешь.

2024-04-26 22:01 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +    public static File getFile() {
убрал данный геттер

2024-04-26 22:02 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +//убрал отсюда мапы, historyManager и айди
убрал все подобные комментарии из кода

2024-04-26 22:02 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +
удалил пустые строки

2024-04-26 22:03 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +// перенес TaskType в отдельный файл
добавил пустую строку

2024-04-26 22:05 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +        try (PrintWriter writer = new PrintWriter(file)) {
поправил данный метод

2024-04-26 22:07 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +                    fileBackedTasksManager.getTaskById(task.getId());
убрал вызов

2024-04-26 22:08 UTC, sixtykz commented on src/main/java/service/InMemoryTaskManager.java
> +    public void assignTaskToEpic(int taskId, int epicId) {
удалил

2024-04-26 22:15 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +    private static File path;
убрал

2024-04-26 22:30 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +            while ((line = br.readLine()) != null) {
убрал

2024-04-26 23:03 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +                    Task task = null;
если правильно все понял, то сделал

2024-04-26 23:04 UTC, sixtykz commented on src/main/java/service/InMemoryTaskManager.java
> +    protected void updateTask(int taskId, String name, Status status, String description) {
удалил

2024-04-26 23:04 UTC, sixtykz commented on src/main/java/tasks/Task.java
> +import main.java.service.FileBackedTasksManager;
убрал

2024-04-26 23:05 UTC, sixtykz commented on src/main/java/tasks/Task.java
> +    public Task(TaskType type, String description) {
убрал

2024-04-26 23:15 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +    public String toString(Task task) {
исправил

2024-04-26 23:15 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +    public static Task fromString(String value) {
исправил

2024-04-27 23:49 UTC, dgumich requested changes

2024-04-27 23:49 UTC, dgumich commented on src/main/java/service/InMemoryTaskManager.java
> +public abstract class InMemoryTaskManager implements TaskManager {
Почему класс стал абстрактным? Какой в этом смысл? Он должен быть обычным, не абстрактным классом.

2024-04-27 23:49 UTC, dgumich commented on src/main/java/service/InMemoryTaskManager.java
> +    public abstract String toString(Task task);
Такого метода не должно быть в InMemoryTaskManager.

2024-04-27 23:49 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +        return task.getTitle() + "," + task.getDescription();
Не правильная реализация метода. По ТЗ мы должны записать (соответственно считать из файла) строку вида 
1,TASK,Task1,NEW,Description task1

2024-04-27 23:49 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +        String[] parts = value.split(",");
Не правильно реализовано считывание и парсинг строки в задачу/подзадачу/эпик.
Мы должны считывать строку вида
1,TASK,Task1,NEW,Description task1,
Нет парсинга айди, типа задачи, состояния.

2024-04-27 23:49 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +        return new Task(name, description, psriority);
Мы должны возвращать или задачу или эпик или подзадачу, в зависимости от считанной строки, а не просто задачу.

2024-04-27 23:49 UTC, dgumich commented on src/main/java/tasks/Task.java
>      private int id;
Так и не добавил поле, типа TaskType, что бы можно было определить, что за тип задачи.

2024-04-27 23:49 UTC, dgumich commented on src/main/java/service/Managers.java
> +            public String toString(Task task) {
Этого не должно быть. Класс  InMemoryTaskManager() не должен быть абстрактным.

2024-04-27 23:49 UTC, dgumich commented on src/main/java/Main.java
> +        Task epic1 = new Task("Epic 1", "Description 2");
Ты ничего не делаешь с задачами, подзадачами. Просто создаешь и всё.

2024-04-27 23:49 UTC, dgumich commented on src/main/java/Main.java
> +        FileBackedTasksManager.loadFromFile(file);
Какой смысл строки 76? Мы загружаем из пустого файла, создаем менеджер, который даже не сохраняем в переменную. То есть всё в пустую.

2024-04-27 23:49 UTC, dgumich commented on src/main/java/Main.java
> +        FileBackedTasksManager fileBackedTasksManager = new FileBackedTasksManager(file);
Менеджер создал, но ничего с ним не сделал.

2024-04-27 23:49 UTC, dgumich commented on src/main/java/Main.java
> +        FileBackedTasksManager fileBackedTasksManager1 = new FileBackedTasksManager(file);
Аналогично, менеджер создан, но ничего с ним не сделал.

2024-04-27 23:49 UTC, dgumich commented on src/main/java/service/FileBackedTasksManager.java
> +                    if (task.getTitle().equals(TaskType.TASK)) {
task.getTitle() возвращает строку, его никак не сравнить с энамом (TaskType.TASK).
Поэтому считывание из файла не сработает.

2024-04-29 09:56 UTC, sixtykz commented on src/main/java/service/InMemoryTaskManager.java
> +public abstract class InMemoryTaskManager implements TaskManager {
исправил

2024-04-29 09:57 UTC, sixtykz commented on src/main/java/service/InMemoryTaskManager.java
> +    public abstract String toString(Task task);
убрал

2024-04-29 10:06 UTC, sixtykz commented on src/main/java/tasks/Task.java
>      private int id;
добавил

2024-04-29 10:07 UTC, sixtykz commented on src/main/java/service/Managers.java
> +            public String toString(Task task) {
убрал

2024-04-29 10:12 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +        return task.getTitle() + "," + task.getDescription();
исправил

2024-04-29 10:45 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +        String[] parts = value.split(",");
исправил

2024-04-29 11:03 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +        return new Task(name, description, psriority);
исправил

2024-04-29 11:29 UTC, sixtykz commented on src/main/java/Main.java
> +        FileBackedTasksManager.loadFromFile(file);
В строке 76 мы загружаем данные из файла (в данном случае из пустого файла) с помощью метода loadFromFile, чтобы подтвердить успешное сохранение и загрузку пустого файла.

2024-05-24 19:49 UTC, TarasovSam reviewed
Олег, привет! Проверил твое задание. Оно еще сыровато, нужны доработки. Оставил соответствующие комментарии с тем, что можно улучшить и что нужно поправить
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку)

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/Main.java
> +        };
А для чего "{ }" ?

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/Main.java
> +        FileBackedTasksManager fileBackedTasksManager1 = new FileBackedTasksManager(file);
С какой целью создал данный экземпляр менеджера?

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/Main.java
> +        FileBackedTasksManager.loadFromFile(file);
Какая цель подтверждения на пустом файле? Ты создаешь переменную file, экземпляр менеджера, вызываешь метод, а результат по факту нулевой. Т.е. действие ради действия
Это лучше сделать на заполненном файле

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
> +
Лишняя пустая строка и далее по коду

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/service/Managers.java
> +        };
Здесь тоже для чего "{ }" прописал?

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/tasks/Task.java
> +    public enum TaskType {
Это следует вынести в отдельный класс enum

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/tasks/Task.java
>  public class Task {
Почему не добавил поле TaskType?

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/ManagerSaveException.java
> +package main.java;
Перенеси собственное исключение в отдельный пакет

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/tasks/Task.java
> +    private static String title;
Почему поля static?

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/tasks/Task.java
> +    public Task(int id, String title, String s, String description) {
1. Название "s" абсолютно не информативно
2. А главное это какой-то не законченный конструктор. Необходимо его поправить

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/tasks/Epic.java
> +        super(id, description, status, description);
У тебя два раза прописан description, а параметр метода title не используется

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/tasks/Epic.java
>      }
Ниже написать не могу
Методы cleanSubtaskIds() и removeSubtask(int id) раздели пустой строкой

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/tasks/Subtask.java
> +        super(id, description, status, description);
Здесь тоже дважды используется description и не используется title

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/tasks/Subtask.java
>      public Subtask(String title, String description, Status status, int epicId) {
Параметр epicId не используется в конструкторе. Либо его убрать, либо использовать

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/service/Managers.java
> +import main.java.tasks.Task;
Импорт не используется - убрать

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/service/InMemoryTaskManager.java
Оставлю комментарий к интерфейсу TaskManager  здесь
1. Не используются импорты на строках 3 и 8 - убрать
2. Есть лишние пустые строки, нужно привести в порядок

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/service/InMemoryTaskManager.java
> +   protected int id;
Строка сдвинута влево относительно остальных

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/tasks/Task.java
> +    public static String getTitle() {
Для чего сделал статичными методы getId() и getTitle()?

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/service/InMemoryHistoryManager.java
>              }
Ниже написать не могу
Класс Node следует вынести в отдельный класс. Сейчас он у тебя даже не вложенный

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
> +        if (taskType.equals(Task.TaskType.TASK)) {
Рекомендую перейти на switch-case
И в методе loadFromFile тоже

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
> +            String description = parts[4];
Эти 4 строки у тебя повторяются 3 раза подряд, т.к. код задублированный
В таких случаях необходимо вынести повторяющийся код в отдельный метод и вызывать его в нужных местах

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/Main.java
> +        Task subTask2 = new Subtask(Subtask.getId(), Subtask.getTitle(), "SubTask 2", "Description 2");
Для чего ты создаешь по 2 задачи, подзадачи, эпика? Ты их нигде не используешь
К тому же у тебя в самом начале метода main уже создано несколько задач

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
> +        return task.getId() + "," + task.getTitle() + "," + task.getStatus() + "," + task.getDescription();
Применение конкатенации - не слишком оптимальное решение. Лучше использовать StringBuilder в таких случаях

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
> +        } else if (taskType.equals(Task.TaskType.SUBTASK)) {
В таких местах у тебя всегда будет false, т.к. ты сравниваешь String и объект TaskType. Они никогда не будут равны

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
> +                    if (task.getTitle().equals(Task.TaskType.TASK)) {
Здесь ты вообще сравниваешь String title (заголовок) и объект TaskType

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
> +            String status = parts[3];
Для статуса есть класс Status, так почему здесь строка??

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
> +            return new Task(id, title, status, description);
Через вызов данного конструктора id будет всегда 0, не смотря на переданный id в параметре
Аналогично для подзадачи и эпика

2024-05-24 19:49 UTC, TarasovSam commented on src/main/java/Main.java
> +    public static void main(String[] args) throws IOException {
Для полноценной демонстрации функционала тебе нужно:
1. Создать задачи, подзадачи, эпики
2. Записать их в файл
3. Считать из файла записанные задачи
4. Вывести их в консоль

2024-05-31 17:39 UTC, TarasovSam reviewed
Олег, провел проверки твоего приложения:
1. У тебя ветка имеет конфликт, который нужно разрешить локально перед слитием и отправлением на проверку
2. Не внес правки в класс Main
3. Не вынес TaskType в отдельный класс и не добавил поле TaskType к задачам
4. Не внес правки в модели Task, Subtask, Epic
5. Не перенеси собственное исключение в отдельный пакет
6. Не внес правки в интерфейс TaskManager
7. Не внес правки для класса Node
8. Не переработал класс FileBackedTasksManager
9. У тебя отсутствует тестирование 
 
Настоятельно рекомендую внимательно прочитать все комментарии, которые тебе оставляли (и я, и предыдущий ревьюер), внеси необходимые правки. И перед отправкой протестируй свое приложение
Жду твою работу на следующую итерацию

2024-05-31 17:39 UTC, TarasovSam commented on src/main/java/service/Managers.java
> -    public static  TaskManager getDefault() {
Почему удалил метод getDefault()?
К тому же нужно либо поменять его реализацию с использованием FileBackedTaskManager, либо создать еще один метод в менеджере и задействовать FileBackedTaskManager

2024-05-31 17:39 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
> +        if (Task.TaskType.TASK.equals(Task.TaskType.TASK)) {
А ты запускал свое приложение? Тестировал его хоть чуть-чуть?

В условиях ты сравниваешь TASK из enum с TASK из enum, далее EPIC с EPIC и SUBTASK с SUBTASK. Т.е. ты считываешь строку, из нее не берешь тип, а сравниваешь одно и тоже между собой. И получается, что у тебя все три условия true абсолютно всегда

2024-05-31 17:39 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
> +            String status = Status.NEW.name();
Почему присваиваешь статус NEW, а не считываешь его из файла
До этого ты его считывал, но оставлял в виде строки. А нужно было считать из файла, но строки привести к объекту Status

2024-06-09 19:55 UTC, TarasovSam reviewed
Олег, проверил твое приложение. Небольшие сподвижки есть, но недочетов еще много (приложение не работает - не записывает в файл, не читает из него). Оставил комментарии, будь внимателен, пожалуйста. И повторюсь, тестируй приложение перед отправкой на проверку

PS у тебя есть конфликт в ветке, его необходимо решить перед отправкой на проверку. Если придет ветка с конфликтом в следующий раз, сразу отправлю на доработку без проверки кода

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/Exceptions/ManagerSaveException.java
Имена пакетов пишутся с маленькой буквы, т.е. переименуй Exceptions в еxceptions

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/service/Node.java
> +class Node {
Модификатор поменяй на public
В остальном все хорошо

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/service/Managers.java
>  public class Managers {
А где метод для новой реализации интерфейса TaskManager через FileBackedTasksManager?

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/tasks/Task.java
>      private String description;
С какой целью сделал статичные поля id и title?

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/tasks/Task.java
> +    public Task(int id, String title, Status s, String description) {
Этот конструктор полностью повторяет конструктор с 9 строки, только параметры местами поменяны 
Дублирующий код следует убирать

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/tasks/Task.java
>      public static int getId() {
Соответственно и методы сделай не статичными

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/tasks/Task.java
>      public String toString() {
Для вывода в консоль лучше передавать не напрямую ссылки на переменные, а использовать соответствующие get'еры
Тоже самое и для подзадачи, и для эпика

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/tasks/TaskType.java
> +public enum TaskType {
Повторю комментарий предыдущего ревьюера
Ты создал enum, но не используешь его в моделях задач/подзадач/эпиков
Введи новое поле в каждой модели:
TaskType taskType = TaskType.[ ... ]

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/tasks/Subtask.java
> +    public Subtask(int id, String title, String status, String description, Status subTaskStatus) {
String status - разве у тебя есть такое поле в данной или родительской модели? Что это вообще??
Ты прописал Status subTaskStatus, String status убери тогда

Так же есть входящий параметр String title, который ты не используешь в конструкторе. Поэтому либо его убрать, либо использовать

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/tasks/Subtask.java
> +        super(1, title, description, status);
Что это за "магическое" число 1??

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/tasks/Subtask.java
>      public Subtask(String title, String description, Status status, int epicId) {
Продублирую
Параметр epicId не используется в конструкторе. Либо его убрать, либо использовать

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/tasks/Subtask.java
В методе toString() вместо epicId пропиши getEpicId()

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/tasks/Subtask.java
>      private final int epicId = 0;
Зачем инициализируешь поле? 
Значение же идентификатора эпика, которому принадлежит подзадача, задается при создании подзадачи (через конструктор, который необходимо доработать)

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/tasks/Epic.java
> +        super(1, title, description, status);
Опять же, что за "магическое" число?

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/tasks/Epic.java
> +    public Epic(int id, String title, Status status, String description) {
Параметр String title, который ты не используешь в конструкторе. Поэтому либо его убрать, либо использовать

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/tasks/Epic.java
>          super(id, description, status, description);
Продублирую
У тебя два раза прописан description, а параметр метода title не используется

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/Main.java
>          FileBackedTasksManager.loadFromFile(file);
Ты приложение запускал, смотрел, как оно отрабатывает?
Я вот запустил, файл tasks.csv у меня создан и не пустой. При этом в консоли я вижу строку "Task list пуст"
Соответственно приложение работает не так, как нужно

Я продублирую комментарий для полноценной демонстрации функционала:
1. Создать задачи, подзадачи, эпики
2. Записать их в файл
3. Считать из файла записанные задачи
4. Вывести их в консоль

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/intefaces/TaskManager.java
Пропишу общий комментарий здесь:
1. Для методов создания, обновления лучше возвращать соответствующий тип объекта (это позволит убрать необходимость использования метода getById, чтобы получить созданный/обновленный объект)
2. Методы getById должны возвращать соответствующий тип объекта, а не быть void
3. Методы print в принципе не относятся к менеджеру задач, поэтому рекомендую их убрать из интерфейса и его реализации, и создать их в классе Main чисто для печати в консоль

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/service/InMemoryTaskManager.java
Строка 14 сдвинута влево относительно остальных

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
Переменная taskType нигде не используется
А вот когда создашь соответствующее поле в моделях, то оно понадобится

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
> +        if (TaskType.TASK.toString().equals(TaskType.TASK)) {
Я же в пачке тебе писал, как нужно сравнивать.. А сейчас у тебя опять идет сравнение строки и объекты, поэтому логическое выражение всегда будет ложным
Пропиши  if (Task.TaskType.TASK.toString().equals(taskType))
Тоже самое для подзадач, эпиков

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
>          } else {
Опять же вместо ветвистого if-else можно использовать switch-case и параметром сделать как раз taskType, в зависимости от которого будешь создавать задачу, подзадачу и эпик

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
> +                    if (task.getTitle().equals(TaskType.TASK)) {
Продублирую
task.getTitle() возвращает строку, его никак не сравнить с энамом (TaskType.TASK)
Поэтому считывание из файла не сработает (и не только из-за этого)
К тому же task.getTitle() - заголовок, а TaskType.TASK - тип ЗАДАЧА, зачем их вообще сравнивать..?

2024-06-09 19:55 UTC, TarasovSam commented on src/main/java/service/FileBackedTasksManager.java
Комментарий для методы save() оставлю здесь
Этот метод должен записывать строку, которую получили из объекта, в файл
А у тебя что он делает? Выводит в консоль
Писатель должен быть такой: BufferedWriter writer = new BufferedWriter(new FileWriter("task.csv"))

2024-06-14 16:36 UTC, sixtykz commented on src/main/java/tasks/TaskType.java
> +public enum TaskType {
не совсем понял, где прописывать это нужно

2024-06-14 16:47 UTC, sixtykz commented on src/main/java/intefaces/TaskManager.java
не совсем понял, что вы имели ввиду

2024-06-14 16:56 UTC, sixtykz commented on src/main/java/service/FileBackedTasksManager.java
> +                    if (task.getTitle().equals(TaskType.TASK)) {
не понимаю вас, что тогда тут нужно сравнивать?

2024-08-09 12:51 UTC, closed without merging